name: tangent_test_solution
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.12.2


dependencies:
  flutter:
    sdk: flutter

  #UI
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.3.0
  cupertino_icons: ^1.0.8


  #Logic
  flutter_bloc: ^9.1.1

  #Networking
  dio: ^5.9.2

  #local storage
  shared_preferences: ^2.5.5

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^6.0.0


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: PlayfairDisplaySC
      fonts:
        - asset: asssets/fonts/PlayfairDisplaySC-Regular.ttf
        - asset: asssets/fonts/PlayfairDisplaySC-Italic.ttf
          style: italic
        - asset: asssets/fonts/PlayfairDisplaySC-Bold.ttf
          weight: 700
        - asset: asssets/fonts/PlayfairDisplaySC-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: asssets/fonts/PlayfairDisplaySC-Black.ttf
          weight: 900
        - asset: asssets/fonts/PlayfairDisplaySC-BlackItalic.ttf
          weight: 900
          style: italic
