name: tangent_test_solution
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.12.2


dependencies:
  flutter:
    sdk: flutter

  #UI
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.3.0
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1


  #Logic
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  #Networking
  dio: ^5.9.2

  #local storage
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^6.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/lottie/

  fonts:
    - family: PlayfairDisplaySC
      fonts:
        - asset: assets/fonts/PlayfairDisplaySC-Regular.ttf
        - asset: assets/fonts/PlayfairDisplaySC-Italic.ttf
          style: italic
        - asset: assets/fonts/PlayfairDisplaySC-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplaySC-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/PlayfairDisplaySC-Black.ttf
          weight: 900
        - asset: assets/fonts/PlayfairDisplaySC-BlackItalic.ttf
          weight: 900
          style: italic
